@host = http://localhost
@port = 5207
@Restaurants_API_HostAddress = {{host}}:{{port}}

GET {{Restaurants_API_HostAddress}}/api/restaurants
Accept: application/json

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/99
Accept: application/json

###

POST {{Restaurants_API_HostAddress}}/api/restaurants/
Content-Type: application/json

{
    "Name": "Al Macarone",
    "Description": "A cheap restaurant serving a italian food.",
    "Category": "Italian Street Food",
    "HasDelivery": true,
    "ContactEmail": "info@macarone.com",
    "ContactNumber": "98377488",
    "City": "Guatemala City",
    "Street": "98 Petapa Avenue",
    "PostalCode": "10-443"
}