@host = http://localhost
@port = 5207
@token = CfDJ8GacPdrsuRxApzCsoX4o3vPmpldHbKiUGNZT3pOkrR173G0JzbMXgAS6Sa2zo0cpvKIbkDNvYkx6ESIT-WL8zMxMrvwuKeP1MAXCg1gVEbNI9yJXMykD_qxKGcL8c31GoxNlQ15D3kTshse-v46zqspzpRj6C7LdDirdlCmfFDDPQ1VJUvumMYsafL5teaUm7gapvG7hYhPBLPNI85XCM0qCFVohu5IZQL6VDCIxg60jN4yNHDax_6wRyUSnIn7mDblT-mbdYKzK8ge_7LuupLxMvRq0isK71j0Ok2ad657KkV4Wr6uGmzL_DWQL3vDiXG-JPoTG178Gm8BYWTx0UhYwaoCi7FWn-4xVbBI-D6NqFr59XRnr62dQTmAZ6iBWRdRJYkGxirl1jCa_keXluQhNpPjVP8W0uIViqlayLBTnPAi5qN9zmgVtsirxyms8YPbJlKn58-uAfoToSbtNJcG8N2Q4MQFUCOerMwTb6d91gf_w2vbbBRsYYfFJ95Y5wayUkVeX2jA2BU0Wt5uCZIYwrPVTuiaI1cakFTS_ZaF-ab4ag0eR4n3HtNbBeTSuzeoClb8DTXRcAvtI6sgMMbMbOVryBKClWm7d5eiKF-0uZf5KCiENLbMqlTSuUckATHROXzsVVM--pkyeDdVwJV2L0PC3pbFp-I4ULaWvWGBgNdRoJUUuJx0xJC-caw3OX3Np2yEDpmk-1e1sQoacolciNsu7rB-olHwiUcHTsGyo7OsH6TSFChpt2B5HNTDvVNwqTvgII5J6Rsbi61zBCxqGpU5BkrObwaJYuAtdD3L8
@Restaurants_API_HostAddress = {{host}}:{{port}}

GET {{Restaurants_API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}
Accept: application/json

###

POST {{Restaurants_API_HostAddress}}/api/restaurants/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Burger King",
    "Description": "A  restaurant serving hamburgers.",
    "Category": "Greasy Street Food",
    "HasDelivery": true,
    "ContactEmail": "info@bk.com",
    "ContactNumber": "998333",
    "City": "Malmo City",
    "Street": "100 Friisgatan",
    "PostalCode": "11-222"
}

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}
Accept: application/json

###

PATCH {{Restaurants_API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Al Macarone",
    "Description": "A cheap restaurant serving a italian food.",
    "Category": "Italian Street Food",
    "HasDelivery": false
}

###

POST {{Restaurants_API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "Name": "Spaguetti Bolognese",
    "Description": "Pasta with meat sauce.",
    "Category": "Guatemalan Street Food",
    "Price": 11,
    "kiloCalories": 100
}

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/3/dishes
Accept: application/json

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/3/dishes/5
Accept: application/json

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/3/dishes
Accept: application/json

###

POST {{Restaurants_API_HostAddress}}/api/identity/register
Content-Type:  application/json

{
    "email": "test@test.com",
    "password": "Password1!"
}

### 

POST {{Restaurants_API_HostAddress}}/api/identity/login
Content-Type:  application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}