name: restaurant-api

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore Restaurants.sln
      - name: Build
        run: dotnet build Restaurants.sln --no-restore
      - name: Build Tests
        run: dotnet build RestaurantsTests.sln --no-restore
      - name: Test
        run: dotnet test RestaurantsTests.sln
