name: restaurant-api-cd

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore Restaurants.sln
      - name: Build
        run: dotnet build Restaurants.sln --no-restore
      - name: Publish
        run: dotnet publish ./Restaurants.API/Restaurants.API.csproj -o ${{env.DOTNET_ROOT}}/api --no-build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api
      

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: api-artifact
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        with:
          # Name of the Azure Web App
          app-name: 'restaurants-webapi-dev'
          # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

  
